# Generated by Django 3.2.3 on 2021-11-09 02:55

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(blank=True, max_length=250, null=True)),
                ('attribute_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_text', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(null=True, upload_to='banner')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='brand_name')),
                ('brand_name', models.CharField(default='Brand', max_length=225, null=True)),
                ('brand_des', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.IntegerField(blank=True, default=0, null=True)),
                ('promo_cart_total', models.IntegerField(blank=True, default=0, null=True)),
                ('cart_ordered', models.BooleanField(default=False)),
                ('delivery_charges', models.IntegerField(blank=True, default=0, null=True)),
                ('grand_total', models.IntegerField(blank=True, default=0, null=True)),
                ('cart_savings_total', models.IntegerField(blank=True, default=0, null=True)),
                ('cart_promo_savings', models.IntegerField(blank=True, default=0, null=True)),
                ('checkout_status', models.BooleanField(default=False)),
                ('checkout_time', models.DateTimeField(auto_now=True, null=True)),
                ('cart_promo_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=225, unique=True)),
                ('cat_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='cat_name')),
                ('cat_des', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_name', models.CharField(max_length=225)),
                ('constant_value', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.IntegerField()),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.CharField(blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HtmlField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hf_name', models.CharField(max_length=255)),
                ('hf_value', models.TextField(blank=True, null=True)),
                ('my_field', tinymce.models.HTMLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(max_length=255)),
                ('logo_image', models.ImageField(null=True, upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('status', models.CharField(default='', max_length=255)),
                ('update_desc', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_desc', models.TextField()),
                ('price', models.IntegerField(null=True)),
                ('apply_discount', models.BooleanField(blank=True, default=False)),
                ('discount_percent', models.IntegerField(null=True)),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
                ('publish_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(blank=True, default=False)),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('product_views', models.IntegerField(blank=True, default=0, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.imagealbum')),
            ],
        ),
        migrations.CreateModel(
            name='Promo_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(choices=[('one_time', 'ONE_TIME'), ('on_demand', 'ON_DEMAND')], default='one_time', max_length=255)),
                ('promo_name', models.CharField(max_length=255)),
                ('promo_code', models.CharField(max_length=255)),
                ('promo_percent', models.IntegerField()),
                ('promo_status', models.BooleanField(default=False)),
                ('promo_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=225, null=True)),
                ('sub_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='sub_cat_name')),
                ('sub_cat_des', models.CharField(max_length=250, null=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('shipped', 'SHIPPED'), ('deliver', 'DELIVER'), ('active', 'ACTIVE'), ('shipped', 'SHIPPED'), ('deliver', 'DELIVER')], default='active', max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliveryaddress')),
                ('order_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('subscribe_status', models.BooleanField(default=False)),
                ('subscribe_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_sub_cat_name', models.CharField(max_length=225, null=True)),
                ('sub_sub_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='sub_sub_cat_name')),
                ('sub_sub_cat_des', models.CharField(max_length=250, null=True)),
                ('sub_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('apply_discount', models.BooleanField(blank=True, default=False)),
                ('discount_percent', models.IntegerField(null=True)),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
                ('total_pcs', models.IntegerField(blank=True, default=1, null=True)),
                ('num_available', models.IntegerField(default=1)),
                ('shipment', models.IntegerField(default=1)),
                ('savings_item', models.IntegerField(blank=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attribute')),
                ('delivery_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.deliverytime')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sub_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sub_sub_category'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=255)),
                ('image', models.ImageField(null=True, upload_to=shop.models.get_upload_path)),
                ('default', models.BooleanField(default=False)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.imagealbum')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('add_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('promo_unit_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('promo_total_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('savings', models.IntegerField(blank=True, default=0, null=True)),
                ('grand_total_item', models.IntegerField(blank=True, default=0, null=True)),
                ('item_hold_time', models.DateTimeField(blank=True, null=True)),
                ('promo_savings', models.IntegerField(blank=True, default=0, null=True)),
                ('total_saving', models.IntegerField(blank=True, default=0, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
