# Generated by Django 3.2.3 on 2025-03-15 17:20

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(blank=True, max_length=250, null=True)),
                ('attribute_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_text', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(null=True, upload_to='banner')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='brand_name')),
                ('brand_name', models.CharField(default='Brand', max_length=225, null=True)),
                ('brand_des', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.IntegerField(blank=True, default=0, null=True)),
                ('promo_cart_total', models.IntegerField(blank=True, default=0, null=True)),
                ('cart_ordered', models.BooleanField(default=False)),
                ('grand_total', models.IntegerField(blank=True, default=0, null=True)),
                ('cart_savings_total', models.IntegerField(blank=True, default=0, null=True)),
                ('cart_promo_savings', models.IntegerField(blank=True, default=0, null=True)),
                ('checkout_status', models.BooleanField(default=False)),
                ('checkout_time', models.DateTimeField(auto_now=True, null=True)),
                ('cart_promo_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('delivery_charges', models.FloatField(blank=True, null=True)),
                ('tcs_delivery_charges', models.FloatField(blank=True, null=True)),
                ('delivery_charges_per_item', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('add_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('item_price', models.IntegerField(blank=True, default=0, null=True)),
                ('item_discount_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('item_discount_price', models.IntegerField(blank=True, default=0, null=True)),
                ('total_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('promo_unit_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('promo_total_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('savings', models.IntegerField(blank=True, default=0, null=True)),
                ('grand_total_item', models.IntegerField(blank=True, default=0, null=True)),
                ('item_hold_time', models.DateTimeField(blank=True, null=True)),
                ('promo_savings', models.IntegerField(blank=True, default=0, null=True)),
                ('total_saving', models.IntegerField(blank=True, default=0, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('delivery_charges_per_item', models.FloatField(blank=True, null=True)),
                ('profit_cad', models.FloatField(blank=True, null=True)),
                ('profit_pkr', models.FloatField(blank=True, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=225, unique=True)),
                ('cat_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='cat_name')),
                ('cat_des', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_name', models.CharField(max_length=225)),
                ('constant_value', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.CharField(blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HtmlField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hf_name', models.CharField(max_length=255)),
                ('hf_value', models.TextField(blank=True, null=True)),
                ('my_field', tinymce.models.HTMLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(max_length=255)),
                ('logo_image', models.ImageField(null=True, upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('status', models.CharField(default='', max_length=255)),
                ('update_desc', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_desc', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('apply_discount', models.BooleanField(blank=True, default=False)),
                ('discount_percent', models.IntegerField(blank=True, null=True)),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(blank=True, default=False)),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('on_sale', models.BooleanField(blank=True, default=False)),
                ('is_preorder', models.BooleanField(blank=True, default=False)),
                ('availability_type', models.CharField(choices=[('InStock', 'InStock'), ('SoldOut', 'SoldOut'), ('PreOrder', 'PreOrder')], default='InStock', max_length=255)),
                ('product_views', models.IntegerField(blank=True, default=0, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.imagealbum')),
                ('product_tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Promo_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(choices=[('one_time', 'ONE_TIME'), ('on_demand', 'ON_DEMAND'), ('tag_based', 'TAG_BASED')], default='one_time', max_length=255)),
                ('promo_name', models.CharField(max_length=255)),
                ('promo_code', models.CharField(max_length=255)),
                ('promo_percent', models.IntegerField()),
                ('promo_status', models.BooleanField(default=False)),
                ('promo_text', models.CharField(blank=True, max_length=255, null=True)),
                ('promo_tag', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment', models.IntegerField(default=1)),
                ('shipment_charges', models.FloatField(blank=True, null=True)),
                ('number_of_items', models.FloatField(blank=True, null=True)),
                ('shipment_charges_per_item', models.FloatField(blank=True, null=True)),
                ('shipment_rate', models.FloatField(blank=True, default=158, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SizeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(default='Newborn', max_length=255)),
                ('size_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='size_name')),
            ],
        ),
        migrations.CreateModel(
            name='SocialDeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('instagram', 'INSTAGRAM'), ('facebook', 'FACEBOOK')], default='instagram', max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(max_length=225, null=True)),
                ('sub_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='sub_cat_name')),
                ('sub_cat_des', models.CharField(max_length=250, null=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='TCSPaymentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_period', models.CharField(blank=True, max_length=255)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('delivery_charges', models.FloatField(blank=True, null=True)),
                ('cod_total', models.IntegerField(blank=True, null=True)),
                ('cod_return', models.IntegerField(blank=True, null=True)),
                ('number_of_orders', models.IntegerField(blank=True, null=True)),
                ('delivery_per_order', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('shipped', 'SHIPPED'), ('deliver', 'DELIVERED'), ('returned', 'RETURNED'), ('cancelled', 'CANCELLED')], default='active', max_length=255)),
                ('payment_type', models.CharField(choices=[('cod', 'COD'), ('bank_transfer', 'BANK TRANSFER'), ('gift', 'GIFT')], default='cod', max_length=255)),
                ('tracking_id', models.CharField(blank=True, max_length=255)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('delivery_charges', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliveryaddress')),
                ('order_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('social_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.socialdeliveryaddress')),
                ('tcsorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.tcspaymentperiod')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('subscribe_status', models.BooleanField(default=False)),
                ('subscribe_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_sub_cat_name', models.CharField(max_length=225, null=True)),
                ('sub_sub_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='sub_sub_cat_name')),
                ('sub_sub_cat_des', models.CharField(max_length=250, null=True)),
                ('sub_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='SizeBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.attribute')),
                ('size_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sizename')),
            ],
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('return_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('return_date', models.DateTimeField(auto_now=True, null=True)),
                ('return_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart_items')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('apply_discount', models.BooleanField(blank=True, default=False)),
                ('discount_percent', models.IntegerField(blank=True, null=True)),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
                ('total_pcs', models.IntegerField(blank=True, default=1, null=True)),
                ('num_available', models.IntegerField(default=1)),
                ('shipment_charges', models.FloatField(blank=True, default=1, null=True)),
                ('savings_item', models.IntegerField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attribute')),
                ('delivery_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliverytime')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shipment')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sub_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sub_sub_category'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=255)),
                ('image', models.ImageField(null=True, upload_to=shop.models.get_upload_path)),
                ('default', models.BooleanField(default=False)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to=shop.models.get_icon_upload_path)),
                ('real_image', models.ImageField(blank=True, null=True, upload_to=shop.models.get_real_upload_path)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.imagealbum')),
            ],
        ),
        migrations.AddField(
            model_name='cart_items',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
