# Generated by Django 3.1.7 on 2021-04-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='cart',
        ),
    ]
