# Generated by Django 3.2.3 on 2021-11-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211109_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='mob_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
