# Generated by Django 3.2.3 on 2021-11-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_deliveryaddress_mob_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='mobile_number',
        ),
    ]
