# Generated by Django 3.1.7 on 2021-04-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_items_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
