# Generated by Django 3.2.3 on 2021-11-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_deliveryaddress_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='mob_number',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='mobile_number',
            field=models.CharField(default='12345', max_length=50),
            preserve_default=False,
        ),
    ]
