# Generated by Django 3.1.7 on 2021-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='add_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
