# Generated by Django 3.2.3 on 2022-01-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_image_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_type',
            field=models.CharField(choices=[('InStock', 'InStock'), ('SoldOut', 'SoldOut'), ('PreOrder', 'PreOrder')], default='InStock', max_length=255),
        ),
    ]
