# Generated by Django 3.1.7 on 2021-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210418_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='add_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
