# Generated by Django 3.1.7 on 2021-04-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210418_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='add_date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
