# Generated by Django 3.1.7 on 2021-04-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210418_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
