# Generated by Django 3.2.3 on 2022-02-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo_code',
            name='promo_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
