# Generated by Django 3.1.7 on 2021-04-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cart_delivery_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_charges',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
