# Generated by Django 3.2.3 on 2022-02-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_promo_code_promo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo_code',
            name='promo_type',
            field=models.CharField(choices=[('one_time', 'ONE_TIME'), ('on_demand', 'ON_DEMAND'), ('tag_based', 'TAG_BASED')], default='one_time', max_length=255),
        ),
    ]
