# Generated by Django 3.1.7 on 2021-04-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210418_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
