# Generated by Django 3.1.7 on 2021-04-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210418_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='grand_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
