# Generated by Django 3.1.7 on 2021-04-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_cart_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='savings_item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
