# Generated by Django 3.2.3 on 2022-07-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_product_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialDeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('instagram', 'INSTAGRAM'), ('facebook', 'FACEBOOK')], default='instagram', max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userorder',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('shipped', 'SHIPPED'), ('deliver', 'DELIVERED'), ('returned', 'RETURNED'), ('cancelled', 'CANCELLED')], default='active', max_length=255),
        ),
        migrations.AddField(
            model_name='userorder',
            name='social_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.socialdeliveryaddress'),
        ),
    ]
