# Generated by Django 3.2.3 on 2022-07-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20220705_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment', models.IntegerField(default=1)),
                ('shipment_charges', models.FloatField(blank=True, null=True)),
                ('number_of_items', models.FloatField(blank=True, null=True)),
                ('shipment_charges_per_item', models.FloatField(blank=True, null=True)),
                ('shipment_rate', models.FloatField(blank=True, default=158, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TCSPaymentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_period', models.CharField(blank=True, max_length=255)),
                ('delivery_charges', models.FloatField(blank=True, null=True)),
                ('cod_total', models.IntegerField(blank=True, null=True)),
                ('cod_return', models.IntegerField(blank=True, null=True)),
                ('number_of_orders', models.IntegerField(blank=True, null=True)),
                ('delivery_per_order', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_charges_per_item',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='tcs_delivery_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='delivery_charges_per_item',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='profit_cad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='profit_pkr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shipment_charges',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='delivery_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='buy_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='tcsorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.tcspaymentperiod'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shipment'),
        ),
    ]
