# Generated by Django 3.1.7 on 2021-04-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_productvariant_savings_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='savings_item',
            field=models.IntegerField(),
        ),
    ]
