# Generated by Django 3.2.3 on 2022-07-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20220711_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='savings_item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
