# Generated by Django 3.2.3 on 2022-08-19 18:14

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_productvariant_savings_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(default='Newborn', max_length=255)),
                ('size_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='size_name')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_preorder',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='SizeBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.attribute')),
                ('size_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sizename')),
            ],
        ),
    ]
