# Generated by Django 3.1.7 on 2021-04-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210420_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_savings_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='savings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
