# Generated by Django 3.1.7 on 2021-04-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20210420_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='grand_total_item',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
