# Generated by Django 3.2.3 on 2022-08-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20220819_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='item_discount_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='item_discount_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='item_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
