# Generated by Django 3.2.3 on 2022-08-29 03:23

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20220829_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='real_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.get_real_upload_path),
        ),
    ]
