# Generated by Django 3.1.7 on 2021-04-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210421_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='UserOrder',
        ),
    ]
