# Generated by Django 3.2.3 on 2022-09-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_image_real_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcspaymentperiod',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'COD'), ('bank_transfer', 'BANK TRANSFER'), ('gift', 'GIFT')], default='cod', max_length=255),
        ),
    ]
