# Generated by Django 3.1.7 on 2021-04-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20210422_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
