# Generated by Django 3.2.3 on 2024-01-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
