# Generated by Django 3.2.3 on 2024-01-05 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20240105_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.imagealbum'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateField(blank=True),
        ),
    ]
