# Generated by Django 3.1.7 on 2021-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210422_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
