# Generated by Django 3.2.3 on 2024-01-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20240105_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
