# Generated by Django 3.1.7 on 2021-04-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20210422_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
