# Generated by Django 3.1.7 on 2021-04-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20210422_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_sub_category',
            name='sub_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.sub_category'),
        ),
    ]
