# Generated by Django 3.2.3 on 2024-01-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_product_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
