# Generated by Django 3.1.7 on 2021-04-22 17:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_sub_sub_category_sub_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='cat_name'),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='sub_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='sub_cat_name'),
        ),
        migrations.AddField(
            model_name='sub_sub_category',
            name='sub_sub_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='sub_sub_cat_name'),
        ),
    ]
