# Generated by Django 3.2.3 on 2024-01-05 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20240105_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='delivery_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliverytime'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shipment'),
        ),
    ]
