# Generated by Django 3.2.3 on 2024-01-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20240105_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
