# Generated by Django 3.2.3 on 2024-01-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20240106_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='order_number',
        ),
        migrations.CreateModel(
            name='MainOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('order_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='main_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.mainorder'),
        ),
    ]
