# Generated by Django 3.2.3 on 2024-05-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20240115_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
