# Generated by Django 3.1.7 on 2021-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_userorder_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='item_hold_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
