# Generated by Django 3.1.7 on 2021-05-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20210502_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constants',
            name='hold_time',
        ),
        migrations.AddField(
            model_name='constants',
            name='constant_name',
            field=models.CharField(default='Brand', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='constants',
            name='constant_value',
            field=models.CharField(default='Brand', max_length=225, null=True),
        ),
    ]
