# Generated by Django 3.1.7 on 2021-05-03 15:42

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20210502_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='sub_sub_cat_name'),
        ),
        migrations.AlterField(
            model_name='constants',
            name='constant_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='constants',
            name='constant_value',
            field=models.CharField(max_length=225),
        ),
    ]
