# Generated by Django 3.1.7 on 2021-05-05 16:28

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20210503_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='brand_name'),
        ),
    ]
