# Generated by Django 3.1.7 on 2021-05-05 18:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20210505_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hf_name', models.CharField(max_length=255)),
                ('hf_value', tinymce.models.HTMLField()),
            ],
        ),
    ]
