# Generated by Django 3.1.7 on 2021-05-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_htmlfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlfield',
            name='hf_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
