# Generated by Django 3.1.7 on 2021-05-05 19:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20210505_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlfield',
            name='my_field',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
