# Generated by Django 3.1.7 on 2021-05-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_htmlfield_my_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_text', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(null=True, upload_to='banner')),
            ],
        ),
    ]
