# Generated by Django 3.1.7 on 2021-05-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_subscriptionlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
        migrations.AddField(
            model_name='cart',
            name='checkout_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='checkout_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
