# Generated by Django 3.1.7 on 2021-05-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20210509_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(max_length=255)),
                ('logo_image', models.ImageField(null=True, upload_to='logo')),
            ],
        ),
    ]
