# Generated by Django 3.2.3 on 2021-05-20 12:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20210513_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='attribute_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='attribute'),
        ),
    ]
