# Generated by Django 3.2.3 on 2021-05-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_deliverytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='delivery_time',
            field=models.ForeignKey(default='3 to 5 Days', on_delete=django.db.models.deletion.CASCADE, to='shop.deliverytime', to_field='delivery_time'),
        ),
        migrations.AlterField(
            model_name='deliverytime',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
