# Generated by Django 3.2.3 on 2021-05-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20210524_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='delivery_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.deliverytime'),
        ),
    ]
