# Generated by Django 3.2.3 on 2021-05-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_alter_productvariant_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='shipment',
            field=models.IntegerField(default=1),
        ),
    ]
