# Generated by Django 3.2.3 on 2021-05-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_productvariant_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
