# Generated by Django 3.2.3 on 2021-06-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_product_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
        migrations.AddField(
            model_name='product',
            name='not_published',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
