# Generated by Django 3.2.3 on 2021-07-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_auto_20210620_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='total_pcs',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
