# Generated by Django 3.2.3 on 2021-07-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_productvariant_total_pcs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(choices=[('one_time', 'ONE_TIME'), ('on_demand', 'ON_DEMAND')], default='one_time', max_length=255)),
                ('promo_name', models.CharField(max_length=255)),
                ('promo_code', models.CharField(max_length=255)),
                ('promo_percent', models.IntegerField()),
                ('promo_status', models.BooleanField(default=False)),
                ('promo_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_promo_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_promo_savings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_cart_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='promo_savings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='promo_total_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='promo_unit_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='total_saving',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='checkout_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
